from . import store
import pathlib, datetime

# faster-whisper model id. "small" ships pre-cached; "medium" downloads on
# first use and gives noticeably better accuracy on clean podcast speech.
DEFAULT_MODEL = "medium"

# Quadro T1000 has ~3.6 GB VRAM — float16 fits "small"/"medium" comfortably.
DEVICE = "cuda"
COMPUTE_TYPE = "float16"


def transcribe(date: str | None = None,
                model_size: str = DEFAULT_MODEL,
                audio_path: str | None = None) -> pathlib.Path:
    """Transcribe the run's episode.mp3 into a timestamped transcript.

    Reads the audio path from episode.json when `audio_path` is not given.
    Writes `transcript.md` (timestamped segments) into the run folder.

    When the audio backend already produced a ground-truth transcript (e.g.
    the podcastfy backend writes ``transcript.md`` directly), this stage is a
    no-op: it detects ``transcript_source: "generated"`` in ``episode.json``
    and returns the existing transcript without running Whisper.
    """
    run = store.run_dir(date)

    # Short-circuit when the backend already wrote a transcript.
    if audio_path is None:
        ep = _read_episode(date)
        if ep is not None and ep.get("transcript_source") == "generated":
            existing = run / "transcript.md"
            if existing.exists():
                backend = ep.get("backend", "audio backend")
                print(f"      transcript already generated by {backend}; skipping Whisper")
                return existing

    from faster_whisper import WhisperModel

    audio = _resolve_audio(audio_path, date)
    if not audio or not audio.exists():
        raise SystemExit(f"cannot transcribe: {audio} not found")

    print(f"      loading whisper ({model_size}, {DEVICE}/{COMPUTE_TYPE})...")
    model = WhisperModel(model_size, device=DEVICE, compute_type=COMPUTE_TYPE)

    print(f"      transcribing {audio} ...")
    segments, info = model.transcribe(str(audio), beam_size=5, vad_filter=True)

    lines = [
        f"# Transcript — {audio.name}",
        "",
        f"Language: {info.language} ({info.language_probability:.2f})  "
        f"Duration: {datetime.timedelta(seconds=round(info.duration))}",
        "",
    ]
    n = 0
    for seg in segments:
        ts = _fmt_ts(seg.start)
        text = seg.text.strip()
        if not text:
            continue
        lines.append(f"**[{ts}]** {text}")
        lines.append("")
        n += 1

    out = run / "transcript.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"      wrote {out.name} ({n} segments)")
    return out


def _resolve_audio(audio_path: str | None, date: str | None) -> pathlib.Path:
    if audio_path:
        return pathlib.Path(audio_path)
    ep = store.read("episode.json", date=date)
    return pathlib.Path(ep["audio_path"])


def _read_episode(date: str | None):
    """Load episode.json if it exists, else return None (non-fatal)."""
    try:
        return store.read("episode.json", date=date)
    except SystemExit:
        return None


def _fmt_ts(seconds: float) -> str:
    s = round(seconds)
    h, r = divmod(s, 3600)
    m, s = divmod(r, 60)
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m:02d}:{s:02d}"
